### ISSUE TITLE
IE浏览器在使用该控件后显示空白

### ISSUE THREAD

**Issue by byblehua** [taojunnan/vuepress-plugin-fulltext-search#1]
IE浏览器在使用该控件后显示空白，有遇到同样问题的吗？有什么方法解决？

**Comment by taojunnan** [comment]
时间太久了不记得了，可能部分依赖有兼容性问题，其他浏览器都正常的吧？

**Comment by byblehua** [comment]
> 时间太久了不记得了，可能部分依赖有兼容性问题，其他浏览器都正常的吧？

其他都正常，就IE有问题。

**Comment by byblehua** [comment]
> 时间太久了不记得了，可能部分依赖有兼容性问题，其他浏览器都正常的吧？

把这个代码注释了，就可以显示，怀疑问题在这里面。
import Flexsearch from 'flexsearch'

**Comment by temu-mall** [comment]
你不IE我不IE，没有IE，前端界从此减少90%的Bug
